services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/opt/homebrew/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s # 20초 동안 헬스 체크 진행
      retries: 10 # 헬스 체크 진행 시간
  backend:
    image: openjdk:21
    ports:
      - '28080:8080'
    volumes:
      - ./api:/app
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "/app/E-Commerce.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://highv.cpcuesoama6y.us-east-1.rds.amazonaws.com:3306/highv
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwer1234
      - SPRING_REDIS_HOST=redis

  frontend:
    image: nginx
    ports:
      - '5173:5173'
    depends_on:
      - backend
  mysql:
    image: mysql:latest
    ports:
      - '23306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=q!w@e#r$1234
      - MYSQL_DATABASE=highv
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwer1234
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
