services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/opt/homebrew/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s # 20초 동안 헬스 체크 진행
      retries: 10 # 헬스 체크 진행 시간
  backend:
    env_file:
      - .env
    image: openjdk:21
    ports:
      - '28080:8080'
    volumes:
      - ./api:/app
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "/app/E-Commerce.jar"]
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_REDIS_HOST: redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s

  frontend:
    image: nginx
    ports:
      - '5173:5173'
    depends_on:
      - backend
  mysql:
    env_file:
      - .env
    image: mysql:latest
    ports:
      - '23306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: highv
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
