version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/opt/homebrew/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  backend:
    container_name: backend
    image: openjdk:22
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
    depends_on:
      - mysql
      - redis
    command: ["java", "-jar", "/app/E-Commerce.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://highv.cpcuesoama6y.us-east-1.rds.amazonaws.com:3306/highv
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwer1234
      - SPRING_REDIS_HOST=redis
  frontend:
      container_name: frontend
      image: ubuntu
      ports:
        - '5173:5173'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  mysql:
    image: mysql:latest
    ports:
      - '23306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=q!w@e#r$1234
      - MYSQL_DATABASE=highv
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwer1234




