spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    username: ${MYSQL_USERNAME}
    url: ${MYSQL_URL}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      repositories:
        enabled: false


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
    auth-code-expiration-millis: 300000 # 5 * 60 * 1000 = 5분

  cache:
    type: redis



logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        transaction: DEBUG

oauth2:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_url: "http://localhost:8080/oauth/login/callback/kakao"
    auth_server_base_url: "https://kauth.kakao.com"
    resource_server_base_url: "https://kapi.kakao.com"
  naver:
    client_id: ${NAVER_CLIENT_ID}
    client_secret: ${NAVER_CLIENT_SECRET}
    redirect_url: "http://localhost:8080/oauth/login/callback/naver/"
    auth_server_base_url: "https://nid.naver.com/oauth2.0"
    resource_server_base_url: "https://openapi.naver.com/v1"


auth:
  jwt:
    issuer: ${AUTH_ISSUER}
    secret: ${AUTH_SECRET}
    accessTokenExpirationHour: 24000
    refreshTokenExpirationHour: 168

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

    region:
      static: "ap-northeast-2"
    stack:
      auto: false
