name: highv
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'openjdk'

      - name: set yml
        run: mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to aws
        run: |
          mv build/libs/E-Commerce-0.0.1-SNAPSHOT.jar ./api/E-Commerce.jar
          java -jar ./api/E-Commerce.jar