name: highv
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6380:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setting env
        run: |
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "AUTH_ISSUER=${{ secrets.AUTH_ISSUER }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}" >> .env
          echo "MYSQL_URL=${{ secrets.MYSQL_URL }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          cat .env

      - name: Set JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up SSH
        uses: appleboy/scp-action@master
        with:
          host: ec2-43-201-108-93.ap-northeast-2.compute.amazonaws.com # 서버 주소
          username : ubuntu
          key : ${{ secrets.EC2_SSH_KEY }}
          port : 22
          source: "./build/libs/*.jar, docker-compose.yml"
          target: "~"
          strip_components: 2

      - name: ssh-command
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ec2-43-201-108-93.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key : ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            kill -9 $(ps -ef | grep java | head -n 1 | awk '{print $2}')
            nohup java -jar *.jar 1> /dev/null 2>&1 &

            


