name: HighV CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: make executable gradlew
        run: chmod +x ./gradlew

      - name: run unittest
        run: |
          ./gradlew clean test